listener_config:
  - name: listener_0
    address: 0.0.0.0
    port: 9000
cluster_config:
  - name: local_service1
    endpoints:
      - address: localhost
        port: 9101
  - name: local_service1
    endpoints:
      - address: localhost
        port: 9102
route_config:
  - prefix: /one
    cluster: local_service1
  - prefix: /two
    cluster: local_service2
tls_config:
  name: test
  cert: /home/ubuntu/tls.crt
  key: /home/ubuntu/tls.key
